---

extends: default

rules:
  braces: &braces { min-spaces-inside: 0, max-spaces-inside: 1 }
  brackets: *braces
  indentation: { spaces: 2, indent-sequences: false }
  line-length: { max: 151 }
  commas: { max-spaces-before: 0, max-spaces-after: 1, min-spaces-after: 0 }
  empty-lines: { max: 1, max-end: 1 }
